build:
	docker build -t crawling .
run:
	docker run -it -d --name seoul crawling
stop:
	docker stop seoul
history:
	docker history seoul
ps:
	docker ps -a
img:
	docker images
rm:
	docker rm seoul
rmi:
	docker rmi crawling